[config]
schemaVersion = "0.0.1"

[package]
namespace = "MrGlim"
name = "ShipLightsTerminal"
versionNumber = "1.0.2"
description = "Terminal commands lights / lightson / lightsoff to control ship lights. Host recommended."
websiteUrl = "https://github.com/ben-hough/lc-mods/tree/main/ShipLightsTerminal"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
iconPath = "icon.png"
readmePath = "README.md"
outdir = "../build-ShipLightsTerminal"

[[build.copy]]
source = "ShipLightsTerminal.dll"
target = "ShipLightsTerminal.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["mods", "serverside", "tweaks-and-quality-of-life", "ai-generated"]
